---
ingress:
  # -- Enable ingress
  enabled: true

  # -- (string) Class name for the ingress resource
  className: nginx

  # -- Host definition for ingress
  hosts:
    - host: semaphore.nevit.ch
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: semaphore-ansible-semaphore
              port:
                name: https

  # -- Optional TLS configuration for ingress
  tls: 
  - hosts:
    - semaphore.nevit.ch  # Update this with your actual domain
    secretName: semaphore-secret-tls  # Your pre-created TLS secret

  # -- Additional annotations for the ingress
  annotations: 
    cert-manager.io/cluster-issuer: letsencrypt-prod # if you're using cert-manager for automatic TLS
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"

general:
  # -- Host to access Semaphore
  host:

  # -- Use Git client implementation
  gitClient: cmd_git

  # -- Working directory for Semaphore
  tmpPath: /tmp/semaphore

  # -- Maximum parallel tasks
  maxParallelTasks: 20

  # -- Disable password login
  passwordLoginDisable: false

  # -- Allow non-admins to create projects
  nonAdminCanCreateProject: true

  # -- Enable usage of remote runners
  useRemoteRunner: false

  # -- Path to SSH config
  sshConfigPath: ~/.ssh/config

  # -- Additional Python packages
  additionalPythonPackages: []

admin:
  # -- Create an local admin user
  create: true

  # -- Fullname for local admin
  fullname: Admin

  # -- Key used within secret for fullname
  fullnameKey: fullname

  # -- Username for local admin
  username: admin

  # -- Key used within secret for username
  usernameKey: username

  # -- Password for local admin
  password: azJxNzV4NjU1OUE1ZiQ=

  # -- Key used within secret for password
  passwordKey: password

  # -- Email for local admin
  email: "s34s3r@gmail.com"

  # -- Key used within secret for email
  emailKey: email

database:
  # -- Type of database backend
  type: postgresql

  # -- Read username from secret
  usernameFromSecret: true

  # -- Username for database
  username: semaphore

  # -- Key used within secret for username
  usernameKey: username

  # -- Password for database
  password: c1FwakJNMGY0aEhDMnEwSUMybGVmME5veE1ESnladTRzTWZ1RHU2UlFEeE1HbmlsZXhscHZIWktaOXFSMFhGUg==

  # -- Key used within secret for password
  passwordKey: password

  # -- Host for database connection
  host: 192.168.1.232 

  # -- Port for database connection
  port: 5432

  # -- Name of the used database
  name: semaphore